vim.cmd "let g:minimap_width = 10"
vim.cmd "let g:minimap_git_colors = 1"
vim.cmd "let g:minimap_highlight_range = 1"
vim.cmd "let g:minimap_highlight_search = 1"

vim.cmd "hi MinimapCurrentLine guifg=#0000AA guibg=#32302f"
vim.cmd "hi MinimapRangeLine guifg=#87C0F9 guibg=#444444"
vim.cmd "let g:minimap_cursor_color = 'MinimapCurrentLine'"
vim.cmd "let g:minimap_range_color = 'MinimapRangeLine'"

vim.cmd "hi MinimapSearch guifg=#DF3232 guibg=#32302f"
vim.cmd "let g:minimap_search_color = 'MinimapSearch'"

vim.cmd "hi MinimapAdd guifg=#7DBB5C guibg=#333333"
vim.cmd "let g:minimap_diffadd_color = 'MinimapAdd'"
vim.cmd "hi MinimapAddRange guifg=#93DB6D guibg=#444444"
vim.cmd "let g:minimap_range_diffadd_color = 'MinimapAddRange'"
vim.cmd "hi MinimapAddCursor guifg=#50793A guibg=#32302f"
vim.cmd "let g:minimap_cursor_diffadd_color = 'MinimapAddCursor'"

vim.cmd "hi MinimapChanged guifg=#D19324 guibg=#333333"
vim.cmd "let g:minimap_diff_color = 'MinimapChanged'"
vim.cmd "hi MinimapChangedRange guifg=#FAC159 guibg=#444444"
vim.cmd "let g:minimap_range_diff_color = 'MinimapChangedRange'"
vim.cmd "hi MinimapChangedCursor guifg=#AA7F32 guibg=#32302f"
vim.cmd "let g:minimap_cursor_diff_color = 'MinimapChangedCursor'"

vim.cmd "hi MinimapRemoved guifg=#AB56C4 guibg=#333333"
vim.cmd "let g:minimap_diffremove_color = 'MinimapRemoved'"
vim.cmd "hi MinimapRemovedRange guifg=#D56BF4 guibg=#444444"
vim.cmd "let g:minimap_range_diffremove_color = 'MinimapRemovedRange'"
vim.cmd "hi MinimapRemovedCursor guifg=#853F99 guibg=#32302f"
vim.cmd "let g:minimap_cursor_diffremove_color = 'MinimapRemovedCursor'"
